# encoding: UTF-8
# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 20160710033531) do

  create_table "clients", force: :cascade do |t|
    t.integer "therapist_id"
    t.string  "medical_record_id"
    t.string  "first_name"
    t.string  "last_name"
    t.string  "date_of_birth"
    t.string  "address"
    t.string  "phone"
  end

  create_table "records", force: :cascade do |t|
    t.integer "client_id"
    t.string  "release_type"
    t.string  "release_description"
    t.string  "release_initialed"
    t.string  "release_releasee"
    t.string  "release_releasee_info"
    t.string  "release_purpose"
    t.string  "ment_orientation"
    t.string  "ment_appearance"
    t.string  "ment_behavior"
    t.string  "ment_speech"
    t.string  "ment_thought"
    t.string  "ment_affect"
    t.string  "ment_mood"
    t.string  "ment_memory"
    t.string  "ment_concentration"
    t.string  "ment_cognition"
    t.string  "ment_sleep"
    t.string  "ment_appetite"
    t.string  "ment_judgment"
    t.string  "ment_insight"
    t.string  "ment_self_behavior"
    t.string  "ment_compulsions"
    t.integer "risk_level"
    t.string  "risk_interventions"
    t.string  "risk_therapist_sign_and_date"
    t.string  "risk_supervisor_sign_and_date"
    t.string  "bio_presenting_problem"
    t.string  "bio_history_presenting_problem"
    t.string  "bio_development"
    t.string  "bio_family_hist_probs"
    t.string  "bio_family_hist_dynamics"
    t.string  "bio_abuse"
    t.string  "bio_reading"
    t.string  "bio_learning_style"
    t.string  "bio_self_assessment"
    t.string  "bio_barriers"
    t.string  "bio_teachable"
    t.string  "bio_family_barriers"
    t.string  "bio_social_function"
    t.string  "bio_community"
    t.string  "bio_culture"
    t.string  "bio_finance"
    t.string  "bio_family_readiness"
    t.string  "bio_strengths_and_challenges"
    t.string  "bio_clinical_analysis"
    t.string  "bio_treatment_recommendations"
    t.string  "bio_other_issues"
    t.string  "bio_dsm"
    t.string  "bio_sign_and_date"
    t.string  "bio_supervisor_sign_and_date"
    t.string  "sui_ideation_past"
    t.string  "sui_ideation_present"
    t.string  "sui_thoughts_past"
    t.string  "sui_thoughts_present"
    t.string  "sui_freq_past"
    t.string  "sui_freq_present"
    t.string  "sui_strength_past"
    t.string  "sui_strength_present"
    t.string  "sui_dur_past"
    t.string  "sui_dur_present"
    t.string  "sui_plan_past"
    t.string  "sui_plan_present"
    t.string  "sui_intent_past"
    t.string  "sui_intent_present"
    t.string  "sui_attempt_past"
    t.string  "sui_attempt_present"
    t.string  "sui_reason_past"
    t.string  "sui_reason_present"
    t.string  "sui_family_past"
    t.string  "sui_family_present"
    t.string  "sui_deterrents_past"
    t.string  "sui_deterrents_present"
    t.string  "sui_selfinjure_past"
    t.string  "sui_selfinjure_present"
    t.string  "hom_thoughts_past"
    t.string  "hom_thoughts_present"
    t.string  "hom_freq_past"
    t.string  "hom_freq_present"
    t.string  "hom_strength_past"
    t.string  "hom_strength_present"
    t.string  "hom_dur_past"
    t.string  "hom_dur_present"
    t.string  "hom_control_past"
    t.string  "hom_control_present"
    t.string  "hom_intent_past"
    t.string  "hom_intent_present"
    t.string  "hom_attempt_past"
    t.string  "hom_attempt_present"
    t.string  "hom_reason_past"
    t.string  "hom_reason_present"
    t.string  "hom_family_past"
    t.string  "hom_family_present"
    t.string  "hom_criminal_past"
    t.string  "hom_criminal_present"
    t.string  "hom_deterrents_past"
    t.string  "hom_deterrents_present"
    t.string  "drug_types"
    t.string  "drug_denies"
    t.string  "drug_method_and_amount"
    t.string  "drug_freq"
    t.integer "drug_age_first_use"
    t.integer "drug_age_last_use"
    t.string  "drug_forty_eight_hours"
    t.string  "drug_thirty_days"
    t.string  "drug_comments"
  end

  create_table "therapists", force: :cascade do |t|
    t.string "username"
    t.string "password_digest"
    t.string "first_name"
    t.string "last_name"
    t.string "license_type"
    t.string "license_number"
  end

end
