john = Therapist.create(username: "user",
password: "password",
email: "john@gmail.com", 
first_name: "John", 
last_name: "Miller", 
license_type: "LCSW",
license_number: "NJ434455566")  

sandee = Client.create( medical_record_id: "GT34233-88",
first_name: "Sandra", 
last_name: "Monroe", 
date_of_birth: "03/14/66", 
address: "453 W.Channing Dr, Jackson, NJ 08878",
phone: "908-545-3222" )

frank = Client.create(medical_record_id: "GT34883-88",
first_name: "Frank", 
last_name: "Gigilli", 
date_of_birth: "09/14/86", 
address: "77666 Velmont Circle, Bledstoe, NJ 09978",
phone: "908-766-3298" )

trish = Client.create(medical_record_id: "GT76554-88",
first_name: "Trish", 
last_name: "O'Malley", 
date_of_birth: "04/14/56", 
address: "890 Hollis Ave, Bledstoe, NJ 09978",
phone: "908-766-7777" )


record1 = Record.create(
release_type: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
release_description: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
release_initialed: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
release_releasee: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
release_releasee_info: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
release_purpose: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
ment_orientation: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
ment_appearance: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
ment_behavior: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
ment_speech: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
ment_thought: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
ment_affect: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
ment_mood: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
ment_memory: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
ment_concentration: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
ment_cognition: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
ment_sleep: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
ment_appetite: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
ment_judgment: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
ment_insight: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
ment_self_behavior: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
ment_compulsions: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
risk_level: 8, 
risk_interventions: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
risk_therapist_sign_and_date: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
risk_supervisor_sign_and_date: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_presenting_problem: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_history_presenting_problem: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_development: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_family_hist_probs: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_family_hist_dynamics: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_abuse: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_reading: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_learning_style: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_self_assessment: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_barriers: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_teachable: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_family_barriers: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_social_function: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_community: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_culture: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_finance: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_family_readiness: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_strengths_and_challenges: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
bio_clinical_analysis: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
bio_treatment_recommendations: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
bio_other_issues: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
bio_dsm: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
bio_sign_and_date: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
bio_supervisor_sign_and_date: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
sui_ideation_past: "Cras tempus pharetra interdum. Suspendisse pharetra tincidunt augue hendrerit lobortis. Donec tincidunt bibendum dolor, in gravida risus tempor a. Praesent luctus fringilla tincidunt. Phasellus efficitur tortor lacus, non faucibus quam vehicula sed.", 
sui_ideation_present: "Cras tempus pharetra interdum. Suspendisse pharetra tincidunt augue hendrerit lobortis. Donec tincidunt bibendum dolor, in gravida risus tempor a. Praesent luctus fringilla tincidunt. Phasellus efficitur tortor lacus, non faucibus quam vehicula sed.", 
sui_thoughts_past: "Cras tempus pharetra interdum. Suspendisse pharetra tincidunt augue hendrerit lobortis. Donec tincidunt bibendum dolor, in gravida risus tempor a. Praesent luctus fringilla tincidunt. Phasellus efficitur tortor lacus, non faucibus quam vehicula sed.", 
sui_thoughts_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
sui_freq_past: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
sui_freq_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
sui_strength_past: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
sui_strength_present: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
sui_dur_past: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
sui_dur_present: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
sui_control_past: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
sui_control_present: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
sui_plan_past: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
sui_plan_present: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
sui_intent_past: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
sui_intent_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
sui_attempt_past: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
sui_attempt_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
sui_reason_past: "Cras tempus pharetra interdum. Suspendisse pharetra tincidunt augue hendrerit lobortis. Donec tincidunt bibendum dolor, in gravida risus tempor a. Praesent luctus fringilla tincidunt. Phasellus efficitur tortor lacus, non faucibus quam vehicula sed.", 
sui_reason_present: "Cras tempus pharetra interdum. Suspendisse pharetra tincidunt augue hendrerit lobortis. Donec tincidunt bibendum dolor, in gravida risus tempor a. Praesent luctus fringilla tincidunt. Phasellus efficitur tortor lacus, non faucibus quam vehicula sed.", 
sui_family_past: "Cras tempus pharetra interdum. Suspendisse pharetra tincidunt augue hendrerit lobortis. Donec tincidunt bibendum dolor, in gravida risus tempor a. Praesent luctus fringilla tincidunt. Phasellus efficitur tortor lacus, non faucibus quam vehicula sed.", 
sui_family_present: "Cras tempus pharetra interdum. Suspendisse pharetra tincidunt augue hendrerit lobortis. Donec tincidunt bibendum dolor, in gravida risus tempor a. Praesent luctus fringilla tincidunt. Phasellus efficitur tortor lacus, non faucibus quam vehicula sed.", 
sui_deterrents_past: "Cras tempus pharetra interdum. Suspendisse pharetra tincidunt augue hendrerit lobortis. Donec tincidunt bibendum dolor, in gravida risus tempor a. Praesent luctus fringilla tincidunt. Phasellus efficitur tortor lacus, non faucibus quam vehicula sed.", 
sui_deterrents_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
sui_selfinjure_past: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
sui_selfinjure_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_ideation_past: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_ideation_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_thoughts_past: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_thoughts_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_freq_past: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_freq_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_strength_past: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_strength_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_dur_past: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_dur_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_control_past: "Cras tempus pharetra interdum. Suspendisse pharetra tincidunt augue hendrerit lobortis. Donec tincidunt bibendum dolor, in gravida risus tempor a. Praesent luctus fringilla tincidunt. Phasellus efficitur tortor lacus, non faucibus quam vehicula sed.", 
hom_control_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_intent_past: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_intent_present: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
hom_plan_past: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
hom_plan_present: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
hom_attempt_past: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
hom_attempt_present: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
hom_reason_past: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
hom_reason_present: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
hom_family_past: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
hom_family_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_criminal_past: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_criminal_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_deterrents_past: "Cras tempus pharetra interdum. Suspendisse pharetra tincidunt augue hendrerit lobortis. Donec tincidunt bibendum dolor, in gravida risus tempor a. Praesent luctus fringilla tincidunt. Phasellus efficitur tortor lacus, non faucibus quam vehicula sed.", 
hom_deterrents_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc." )

record2 = Record.create(

release_type: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
release_description: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
release_initialed: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
release_releasee: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
release_releasee_info: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
release_purpose: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
ment_orientation: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
ment_appearance: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
ment_behavior: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
ment_speech: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
ment_thought: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
ment_affect: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
ment_mood: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
ment_memory: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
ment_concentration: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
ment_cognition: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
ment_sleep: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
ment_appetite: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
ment_judgment: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
ment_insight: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
ment_self_behavior: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
ment_compulsions: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
risk_level: 9, 
risk_interventions: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
risk_therapist_sign_and_date: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
risk_supervisor_sign_and_date: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_presenting_problem: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_history_presenting_problem: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_development: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_family_hist_probs: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_family_hist_dynamics: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_abuse: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_reading: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_learning_style: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_self_assessment: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_barriers: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_teachable: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_family_barriers: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_social_function: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_community: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_culture: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_finance: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_family_readiness: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_strengths_and_challenges: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
bio_clinical_analysis: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
bio_treatment_recommendations: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
bio_other_issues: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
bio_dsm: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
bio_sign_and_date: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
bio_supervisor_sign_and_date: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
sui_ideation_past: "Cras tempus pharetra interdum. Suspendisse pharetra tincidunt augue hendrerit lobortis. Donec tincidunt bibendum dolor, in gravida risus tempor a. Praesent luctus fringilla tincidunt. Phasellus efficitur tortor lacus, non faucibus quam vehicula sed.", 
sui_ideation_present: "Cras tempus pharetra interdum. Suspendisse pharetra tincidunt augue hendrerit lobortis. Donec tincidunt bibendum dolor, in gravida risus tempor a. Praesent luctus fringilla tincidunt. Phasellus efficitur tortor lacus, non faucibus quam vehicula sed.", 
sui_thoughts_past: "Cras tempus pharetra interdum. Suspendisse pharetra tincidunt augue hendrerit lobortis. Donec tincidunt bibendum dolor, in gravida risus tempor a. Praesent luctus fringilla tincidunt. Phasellus efficitur tortor lacus, non faucibus quam vehicula sed.", 
sui_thoughts_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
sui_freq_past: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
sui_freq_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
sui_strength_past: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
sui_strength_present: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
sui_dur_past: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
sui_dur_present: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
sui_control_past: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
sui_control_present: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
sui_plan_past: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
sui_plan_present: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
sui_intent_past: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
sui_intent_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
sui_attempt_past: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
sui_attempt_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
sui_reason_past: "Cras tempus pharetra interdum. Suspendisse pharetra tincidunt augue hendrerit lobortis. Donec tincidunt bibendum dolor, in gravida risus tempor a. Praesent luctus fringilla tincidunt. Phasellus efficitur tortor lacus, non faucibus quam vehicula sed.", 
sui_reason_present: "Cras tempus pharetra interdum. Suspendisse pharetra tincidunt augue hendrerit lobortis. Donec tincidunt bibendum dolor, in gravida risus tempor a. Praesent luctus fringilla tincidunt. Phasellus efficitur tortor lacus, non faucibus quam vehicula sed.", 
sui_family_past: "Cras tempus pharetra interdum. Suspendisse pharetra tincidunt augue hendrerit lobortis. Donec tincidunt bibendum dolor, in gravida risus tempor a. Praesent luctus fringilla tincidunt. Phasellus efficitur tortor lacus, non faucibus quam vehicula sed.", 
sui_family_present: "Cras tempus pharetra interdum. Suspendisse pharetra tincidunt augue hendrerit lobortis. Donec tincidunt bibendum dolor, in gravida risus tempor a. Praesent luctus fringilla tincidunt. Phasellus efficitur tortor lacus, non faucibus quam vehicula sed.", 
sui_deterrents_past: "Cras tempus pharetra interdum. Suspendisse pharetra tincidunt augue hendrerit lobortis. Donec tincidunt bibendum dolor, in gravida risus tempor a. Praesent luctus fringilla tincidunt. Phasellus efficitur tortor lacus, non faucibus quam vehicula sed.", 
sui_deterrents_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
sui_selfinjure_past: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
sui_selfinjure_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_ideation_past: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_ideation_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_thoughts_past: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_thoughts_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_freq_past: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_freq_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_strength_past: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_strength_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_dur_past: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_dur_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_control_past: "Cras tempus pharetra interdum. Suspendisse pharetra tincidunt augue hendrerit lobortis. Donec tincidunt bibendum dolor, in gravida risus tempor a. Praesent luctus fringilla tincidunt. Phasellus efficitur tortor lacus, non faucibus quam vehicula sed.", 
hom_control_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_intent_past: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_intent_present: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
hom_plan_past: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
hom_plan_present: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
hom_attempt_past: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
hom_attempt_present: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
hom_reason_past: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
hom_reason_present: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
hom_family_past: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
hom_family_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_criminal_past: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_criminal_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_deterrents_past: "Cras tempus pharetra interdum. Suspendisse pharetra tincidunt augue hendrerit lobortis. Donec tincidunt bibendum dolor, in gravida risus tempor a. Praesent luctus fringilla tincidunt. Phasellus efficitur tortor lacus, non faucibus quam vehicula sed.", 
hom_deterrents_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc." )

record3 = Record.create(

release_type: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
release_description: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
release_initialed: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
release_releasee: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
release_releasee_info: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
release_purpose: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
ment_orientation: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
ment_appearance: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
ment_behavior: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
ment_speech: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
ment_thought: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
ment_affect: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
ment_mood: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
ment_memory: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
ment_concentration: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
ment_cognition: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
ment_sleep: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
ment_appetite: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
ment_judgment: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
ment_insight: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
ment_self_behavior: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
ment_compulsions: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
risk_level: 5, 
risk_interventions: 
"Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
risk_therapist_sign_and_date: 
"Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
risk_supervisor_sign_and_date: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_presenting_problem: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_history_presenting_problem: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_development: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_family_hist_probs: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_family_hist_dynamics: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_abuse: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_reading: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_learning_style: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_self_assessment: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_barriers: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_teachable: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_family_barriers: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_social_function: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_community: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_culture: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_finance: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_family_readiness: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_strengths_and_challenges: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
bio_clinical_analysis: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
bio_treatment_recommendations: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
bio_other_issues: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
bio_dsm: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
bio_sign_and_date: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
bio_supervisor_sign_and_date: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
sui_ideation_past: "Cras tempus pharetra interdum. Suspendisse pharetra tincidunt augue hendrerit lobortis. Donec tincidunt bibendum dolor, in gravida risus tempor a. Praesent luctus fringilla tincidunt. Phasellus efficitur tortor lacus, non faucibus quam vehicula sed.", 
sui_ideation_present: "Cras tempus pharetra interdum. Suspendisse pharetra tincidunt augue hendrerit lobortis. Donec tincidunt bibendum dolor, in gravida risus tempor a. Praesent luctus fringilla tincidunt. Phasellus efficitur tortor lacus, non faucibus quam vehicula sed.", 
sui_thoughts_past: "Cras tempus pharetra interdum. Suspendisse pharetra tincidunt augue hendrerit lobortis. Donec tincidunt bibendum dolor, in gravida risus tempor a. Praesent luctus fringilla tincidunt. Phasellus efficitur tortor lacus, non faucibus quam vehicula sed.", 
sui_thoughts_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
sui_freq_past: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
sui_freq_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
sui_strength_past: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
sui_strength_present: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
sui_dur_past: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
sui_dur_present: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
sui_control_past: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
sui_control_present: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
sui_plan_past: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
sui_plan_present: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
sui_intent_past: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
sui_intent_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
sui_attempt_past: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
sui_attempt_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
sui_reason_past: "Cras tempus pharetra interdum. Suspendisse pharetra tincidunt augue hendrerit lobortis. Donec tincidunt bibendum dolor, in gravida risus tempor a. Praesent luctus fringilla tincidunt. Phasellus efficitur tortor lacus, non faucibus quam vehicula sed.", 
sui_reason_present: "Cras tempus pharetra interdum. Suspendisse pharetra tincidunt augue hendrerit lobortis. Donec tincidunt bibendum dolor, in gravida risus tempor a. Praesent luctus fringilla tincidunt. Phasellus efficitur tortor lacus, non faucibus quam vehicula sed.", 
sui_family_past: "Cras tempus pharetra interdum. Suspendisse pharetra tincidunt augue hendrerit lobortis. Donec tincidunt bibendum dolor, in gravida risus tempor a. Praesent luctus fringilla tincidunt. Phasellus efficitur tortor lacus, non faucibus quam vehicula sed.", 
sui_family_present: "Cras tempus pharetra interdum. Suspendisse pharetra tincidunt augue hendrerit lobortis. Donec tincidunt bibendum dolor, in gravida risus tempor a. Praesent luctus fringilla tincidunt. Phasellus efficitur tortor lacus, non faucibus quam vehicula sed.", 
sui_deterrents_past: "Cras tempus pharetra interdum. Suspendisse pharetra tincidunt augue hendrerit lobortis. Donec tincidunt bibendum dolor, in gravida risus tempor a. Praesent luctus fringilla tincidunt. Phasellus efficitur tortor lacus, non faucibus quam vehicula sed.", 
sui_deterrents_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
sui_selfinjure_past: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
sui_selfinjure_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_ideation_past: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_ideation_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_thoughts_past: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_thoughts_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_freq_past: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_freq_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_strength_past: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_strength_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_dur_past: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_dur_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_control_past: "Cras tempus pharetra interdum. Suspendisse pharetra tincidunt augue hendrerit lobortis. Donec tincidunt bibendum dolor, in gravida risus tempor a. Praesent luctus fringilla tincidunt. Phasellus efficitur tortor lacus, non faucibus quam vehicula sed.", 
hom_control_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_intent_past: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_intent_present: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
hom_plan_past: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
hom_plan_present: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
hom_attempt_past: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
hom_attempt_present: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
hom_reason_past: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
hom_reason_present: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
hom_family_past: "Phasellus ac facilisis justo, et euismod felis. Duis in sollicitudin nisl. Praesent quis justo sit amet enim lacinia dignissim.", 
hom_family_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_criminal_past: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_criminal_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_deterrents_past: "Cras tempus pharetra interdum. Suspendisse pharetra tincidunt augue hendrerit lobortis. Donec tincidunt bibendum dolor, in gravida risus tempor a. Praesent luctus fringilla tincidunt. Phasellus efficitur tortor lacus, non faucibus quam vehicula sed.", 
hom_deterrents_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc." )


john.save
record1.client_id = frank.id
record2.client_id = sandee.id
record3.client_id = trish.id
frank.therapist_id = john.id
sandee.therapist_id = john.id
trish.therapist_id = john.id
frank.save
sandee.save
trish.save
record1.save
record2.save
record3.save


