john = Therapist.create(username: "user",
password: "password", 
first_name: "John", 
last_name: "Miller", 
license_type: "LCSW",
license_number: "NJ434455566")  

peter = Therapist.create(username: "pete",
password: "password", 
first_name: "Pete", 
last_name: "Johnson", 
license_type: "LCSW",
license_number: "NJ434476566") 




sandee = Client.create( medical_record_id: "GT34233-88",
first_name: "Sandra", 
last_name: "Monroe", 
date_of_birth: "03/14/66", 
address: "453 W.Channing Dr, Jackson, NJ 08878",
phone: "908-545-3222" )

frank = Client.create(medical_record_id: "GT34883-88",
first_name: "Frank", 
last_name: "Gigilli", 
date_of_birth: "09/14/86", 
address: "77666 Velmont Circle, Bledstoe, NJ 09978",
phone: "908-766-3298" )


record1 = Record.create(
release_type: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
release_description: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
release_initialed: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
release_releasee: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
release_releasee_info: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
release_purpose: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
ment_orientation: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
ment_appearance: "Fair", 
ment_behavior: "Fair", 
ment_speech: "Fair", 
ment_thought: "Fair", 
ment_affect: "Fair", 
ment_mood: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
ment_memory: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
ment_concentration: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
ment_cognition: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
ment_sleep: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
ment_appetite: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
ment_judgment: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
ment_insight: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
ment_self_behavior: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
ment_compulsions: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
risk_level: "Fair", 
risk_interventions: "Fair", 
risk_therapist_sign_and_date: "Fair", 
risk_supervisor_sign_and_date: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_presenting_problem: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_history_presenting_problem: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_development: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_family_hist_probs: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_family_hist_dynamics: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_abuse: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_reading: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_learning_style: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_self_assessment: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_barriers: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_teachable: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_family_barriers: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_social_function: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_community: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_culture: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_finance: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_family_readiness: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_strengths_and_challenges: "Fair", 
bio_clinical_analysis: "Fair", 
bio_treatment_recommendations: "Fair", 
bio_other_issues: "Fair", 
bio_dsm: "Fair", 
bio_sign_and_date: "Fair", 
bio_supervisor_sign_and_date: "Fair", 
sui_ideation_past: "Cras tempus pharetra interdum. Suspendisse pharetra tincidunt augue hendrerit lobortis. Donec tincidunt bibendum dolor, in gravida risus tempor a. Praesent luctus fringilla tincidunt. Phasellus efficitur tortor lacus, non faucibus quam vehicula sed.", 
sui_ideation_present: "Cras tempus pharetra interdum. Suspendisse pharetra tincidunt augue hendrerit lobortis. Donec tincidunt bibendum dolor, in gravida risus tempor a. Praesent luctus fringilla tincidunt. Phasellus efficitur tortor lacus, non faucibus quam vehicula sed.", 
sui_thoughts_past: "Cras tempus pharetra interdum. Suspendisse pharetra tincidunt augue hendrerit lobortis. Donec tincidunt bibendum dolor, in gravida risus tempor a. Praesent luctus fringilla tincidunt. Phasellus efficitur tortor lacus, non faucibus quam vehicula sed.", 
sui_thoughts_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
sui_freq_past: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
sui_freq_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
sui_strength_past: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
sui_strength_present: "Fair", 
sui_dur_past: "Fair", 
sui_dur_present: "Fair", 
sui_control_past: "Fair", 
sui_control_present: "Fair", 
sui_plan_past: "Fair", 
sui_plan_present: "Fair", 
sui_intent_past: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
sui_intent_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
sui_attempt_past: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
sui_attempt_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
sui_reason_past: "Cras tempus pharetra interdum. Suspendisse pharetra tincidunt augue hendrerit lobortis. Donec tincidunt bibendum dolor, in gravida risus tempor a. Praesent luctus fringilla tincidunt. Phasellus efficitur tortor lacus, non faucibus quam vehicula sed.", 
sui_reason_present: "Cras tempus pharetra interdum. Suspendisse pharetra tincidunt augue hendrerit lobortis. Donec tincidunt bibendum dolor, in gravida risus tempor a. Praesent luctus fringilla tincidunt. Phasellus efficitur tortor lacus, non faucibus quam vehicula sed.", 
sui_family_past: "Cras tempus pharetra interdum. Suspendisse pharetra tincidunt augue hendrerit lobortis. Donec tincidunt bibendum dolor, in gravida risus tempor a. Praesent luctus fringilla tincidunt. Phasellus efficitur tortor lacus, non faucibus quam vehicula sed.", 
sui_family_present: "Cras tempus pharetra interdum. Suspendisse pharetra tincidunt augue hendrerit lobortis. Donec tincidunt bibendum dolor, in gravida risus tempor a. Praesent luctus fringilla tincidunt. Phasellus efficitur tortor lacus, non faucibus quam vehicula sed.", 
sui_deterrents_past: "Cras tempus pharetra interdum. Suspendisse pharetra tincidunt augue hendrerit lobortis. Donec tincidunt bibendum dolor, in gravida risus tempor a. Praesent luctus fringilla tincidunt. Phasellus efficitur tortor lacus, non faucibus quam vehicula sed.", 
sui_deterrents_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
sui_selfinjure_past: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
sui_selfinjure_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_ideation_past: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_ideation_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_thoughts_past: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_thoughts_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_freq_past: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_freq_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_strength_past: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_strength_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_dur_past: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_dur_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_control_past: "Cras tempus pharetra interdum. Suspendisse pharetra tincidunt augue hendrerit lobortis. Donec tincidunt bibendum dolor, in gravida risus tempor a. Praesent luctus fringilla tincidunt. Phasellus efficitur tortor lacus, non faucibus quam vehicula sed.", 
hom_control_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_intent_past: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_intent_present: "Fair", 
hom_plan_past: "Fair", 
hom_plan_present: "Fair", 
hom_attempt_past: "Fair", 
hom_attempt_present: "Fair", 
hom_reason_past: "Fair", 
hom_reason_present: "Fair", 
hom_family_past: "Fair", 
hom_family_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_criminal_past: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_criminal_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_deterrents_past: "Cras tempus pharetra interdum. Suspendisse pharetra tincidunt augue hendrerit lobortis. Donec tincidunt bibendum dolor, in gravida risus tempor a. Praesent luctus fringilla tincidunt. Phasellus efficitur tortor lacus, non faucibus quam vehicula sed.", 
hom_deterrents_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc." )

record2 = Record.create(

release_type: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
release_description: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
release_initialed: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
release_releasee: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
release_releasee_info: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
release_purpose: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
ment_orientation: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
ment_appearance: "Fair", 
ment_behavior: "Fair", 
ment_speech: "Fair", 
ment_thought: "Fair", 
ment_affect: "Fair", 
ment_mood: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
ment_memory: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
ment_concentration: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
ment_cognition: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
ment_sleep: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
ment_appetite: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
ment_judgment: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
ment_insight: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
ment_self_behavior: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
ment_compulsions: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
risk_level: "Fair", 
risk_interventions: "Fair", 
risk_therapist_sign_and_date: "Fair", 
risk_supervisor_sign_and_date: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_presenting_problem: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_history_presenting_problem: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_development: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_family_hist_probs: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_family_hist_dynamics: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_abuse: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_reading: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_learning_style: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_self_assessment: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_barriers: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_teachable: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_family_barriers: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_social_function: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_community: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_culture: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_finance: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_family_readiness: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
bio_strengths_and_challenges: "Fair", 
bio_clinical_analysis: "Fair", 
bio_treatment_recommendations: "Fair", 
bio_other_issues: "Fair", 
bio_dsm: "Fair", 
bio_sign_and_date: "Fair", 
bio_supervisor_sign_and_date: "Fair", 
sui_ideation_past: "Cras tempus pharetra interdum. Suspendisse pharetra tincidunt augue hendrerit lobortis. Donec tincidunt bibendum dolor, in gravida risus tempor a. Praesent luctus fringilla tincidunt. Phasellus efficitur tortor lacus, non faucibus quam vehicula sed.", 
sui_ideation_present: "Cras tempus pharetra interdum. Suspendisse pharetra tincidunt augue hendrerit lobortis. Donec tincidunt bibendum dolor, in gravida risus tempor a. Praesent luctus fringilla tincidunt. Phasellus efficitur tortor lacus, non faucibus quam vehicula sed.", 
sui_thoughts_past: "Cras tempus pharetra interdum. Suspendisse pharetra tincidunt augue hendrerit lobortis. Donec tincidunt bibendum dolor, in gravida risus tempor a. Praesent luctus fringilla tincidunt. Phasellus efficitur tortor lacus, non faucibus quam vehicula sed.", 
sui_thoughts_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
sui_freq_past: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
sui_freq_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
sui_strength_past: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
sui_strength_present: "Fair", 
sui_dur_past: "Fair", 
sui_dur_present: "Fair", 
sui_control_past: "Fair", 
sui_control_present: "Fair", 
sui_plan_past: "Fair", 
sui_plan_present: "Fair", 
sui_intent_past: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
sui_intent_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
sui_attempt_past: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
sui_attempt_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
sui_reason_past: "Cras tempus pharetra interdum. Suspendisse pharetra tincidunt augue hendrerit lobortis. Donec tincidunt bibendum dolor, in gravida risus tempor a. Praesent luctus fringilla tincidunt. Phasellus efficitur tortor lacus, non faucibus quam vehicula sed.", 
sui_reason_present: "Cras tempus pharetra interdum. Suspendisse pharetra tincidunt augue hendrerit lobortis. Donec tincidunt bibendum dolor, in gravida risus tempor a. Praesent luctus fringilla tincidunt. Phasellus efficitur tortor lacus, non faucibus quam vehicula sed.", 
sui_family_past: "Cras tempus pharetra interdum. Suspendisse pharetra tincidunt augue hendrerit lobortis. Donec tincidunt bibendum dolor, in gravida risus tempor a. Praesent luctus fringilla tincidunt. Phasellus efficitur tortor lacus, non faucibus quam vehicula sed.", 
sui_family_present: "Cras tempus pharetra interdum. Suspendisse pharetra tincidunt augue hendrerit lobortis. Donec tincidunt bibendum dolor, in gravida risus tempor a. Praesent luctus fringilla tincidunt. Phasellus efficitur tortor lacus, non faucibus quam vehicula sed.", 
sui_deterrents_past: "Cras tempus pharetra interdum. Suspendisse pharetra tincidunt augue hendrerit lobortis. Donec tincidunt bibendum dolor, in gravida risus tempor a. Praesent luctus fringilla tincidunt. Phasellus efficitur tortor lacus, non faucibus quam vehicula sed.", 
sui_deterrents_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
sui_selfinjure_past: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
sui_selfinjure_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_ideation_past: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_ideation_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_thoughts_past: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_thoughts_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_freq_past: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_freq_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_strength_past: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_strength_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_dur_past: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_dur_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_control_past: "Cras tempus pharetra interdum. Suspendisse pharetra tincidunt augue hendrerit lobortis. Donec tincidunt bibendum dolor, in gravida risus tempor a. Praesent luctus fringilla tincidunt. Phasellus efficitur tortor lacus, non faucibus quam vehicula sed.", 
hom_control_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_intent_past: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_intent_present: "Fair", 
hom_plan_past: "Fair", 
hom_plan_present: "Fair", 
hom_attempt_past: "Fair", 
hom_attempt_present: "Fair", 
hom_reason_past: "Fair", 
hom_reason_present: "Fair", 
hom_family_past: "Fair", 
hom_family_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_criminal_past: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_criminal_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc.", 
hom_deterrents_past: "Cras tempus pharetra interdum. Suspendisse pharetra tincidunt augue hendrerit lobortis. Donec tincidunt bibendum dolor, in gravida risus tempor a. Praesent luctus fringilla tincidunt. Phasellus efficitur tortor lacus, non faucibus quam vehicula sed.", 
hom_deterrents_present: "Quisque lobortis purus est, a porttitor mi venenatis sed. Vivamus efficitur commodo neque, et faucibus nunc." )



record1.client_id = frank.id
record2.client_id = sandee.id
sandee.therapist_id = peter.id
frank.therapist_id = john.id
frank.save
sandee.save
peter.save
john.save
record1.save
record2.save


